version: "3.3"
services:
  blobfuse:
    container_name: adls-blobfuse
    build:
      context: .
      dockerfile: dockerfileblobfuse
    ports:
      - "80:5000"
    image: adls-blobfuse:1.0
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    env_file:
      - docker.env
    command: >
       bash -c "blobfuse /mnt/adls --tmp-path=/mnt/blobfusetmp  --container-name=images --basic-remount-check=true --use-adls=false;
       flask run --host=0.0.0.0
       && tail -f /dev/null"