apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "containeraksdemo-dbappsettings" # to be re-used within the deployment yaml volumeAttributes section. 
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: sqlsecrets                                        # name of the Kubernetes secret object
    type: Opaque                                                  # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
    data:
    # - key: HOST-DB                                               # data field to populate
    #   objectName: HOST_DB                                        # name of the mounted content to sync; this could be the object name or the object alias
    - key: HOST_DB                                               # data field to populate
      objectName: HOST_DB                                        # name of the mounted content to sync; this could be the object name or the object alias
    - key: HOST_AZUREDB
      objectName: HOST_AZUREDB
    - key: HOST_USER
      objectName: HOST_USER
    - key: HOST_PASSWORD
      objectName: HOST_PASSWORD
    - key: APPLICATIONINSIGHTS_CONNECTION_STRING
      objectName: APPLICATIONINSIGHTS_CONNECTION_STRING
      
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "b9cda09a-2262-4b52-996d-3318d7275f76"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "uploadfilesapp"        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |                         # the different secrets stored in the KV to retrieve
      array:
        - |
          objectName: HOST-DB
          objectAlias: HOST_DB     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: HOST-AZUREDB
          objectAlias: HOST_AZUREDB
          objectType: secret
          objectVersion: ""
        - |
          objectName: HOST-USER
          objectAlias: HOST_USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: HOST-PASSWORD
          objectAlias: HOST_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: APPLICATIONINSIGHTS-CONNECTION-STRING
          objectAlias: APPLICATIONINSIGHTS_CONNECTION_STRING
          objectType: secret
          objectVersion: ""
    tenantId: "6c754086-7408-464c-942f-489b9ce8446b"                 # The tenant ID of the key vault
  