---
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: sa-blob-fuse # name of storage class 
provisioner: blob.csi.azure.com
reclaimPolicy: Retain # Delete or Retain 
volumeBindingMode: Immediate
mountOptions:
- -o allow_other
- --file-cache-timeout-in-seconds=120
- --use-attr-cache=true
- --cancel-list-on-mount-seconds=10
- -o attr_timeout=120
- -o entry_timeout=120
- -o negative_timeout=120
- --log-level=LOG_WARNING
- --cache-size-mb=1000
parameters:
  # below parameters used to bring your own storage account and container
  # the storage account and the key are set in the secret sa-secret. 
  csi.storage.k8s.io/provisioner-secret-name: sa-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: sa-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  volumeAttributes.containerName: images
